import type { OptionCategory, WorldOptionKey } from "@palserver/shared";

/** zh_tw labels — carried over from v1 locales where available. */
export const CATEGORY_LABELS: Record<OptionCategory, string> = {
  server: "伺服器",
  world: "世界",
  pal: "帕魯",
  player: "玩家",
  guild: "公會",
  build: "建築",
  drop: "物品掉落",
};

export const OPTION_LABELS: Record<WorldOptionKey, string> = {
  ServerName: "伺服器名稱",
  ServerDescription: "伺服器描述",
  ServerPassword: "伺服器密碼",
  AdminPassword: "管理員密碼",
  ServerPlayerMaxNum: "玩家數上限",
  CoopPlayerMaxNum: "合作玩家數上限",
  PublicIP: "公開 IP 位址",
  PublicPort: "對外顯示埠(不影響實際連線埠)",
  bIsMultiplay: "開啟多人遊戲",
  bShowPlayerList: "展示玩家列表",
  bIsShowJoinLeftMessage: "顯示加入/離開訊息",
  RESTAPIEnabled: "啟用 REST API",
  RESTAPIPort: "REST API 端口",
  RCONEnabled: "啟用 RCON",
  RCONPort: "RCON 端口",
  ChatPostLimitPerMinute: "每分鐘聊天訊息上限",
  LogFormatType: "日誌格式",
  bIsUseBackupSaveData: "啟用存檔備份",
  AutoSaveSpan: "自動存檔間隔(秒)",
  Region: "伺服器地區",
  CrossplayPlatforms: "跨平台連線平台",
  BanListURL: "封禁名單網址",
  bUseAuth: "啟用官方帳號驗證",
  bAllowClientMod: "允許客戶端模組",
  bEnableVoiceChat: "啟用語音聊天",
  VoiceChatMaxVolumeDistance: "語音最大可聽距離",
  VoiceChatZeroVolumeDistance: "語音最小可聽距離",
  AutoTransferMasterCheckIntervalSeconds: "物品自動轉移檢查間隔(秒)",
  AutoTransferMasterThresholdDays: "物品自動轉移天數門檻",
  ItemContainerForceMarkDirtyInterval: "物品容器強制同步間隔(秒)",
  MaxGuildsPerFrame: "每幀處理公會數量上限",
  PlayerDataPalStorageUpdateCheckTickInterval: "玩家帕魯箱更新檢查間隔",

  PalCaptureRate: "捕獲機率倍率",
  PalSpawnNumRate: "帕魯出現數量倍率",
  PalDamageRateAttack: "帕魯攻擊傷害倍率",
  PalDamageRateDefense: "帕魯承受傷害倍率",
  PalStomachDecreaceRate: "帕魯飽食度降低倍率",
  PalStaminaDecreaceRate: "帕魯耐力降低倍率",
  PalAutoHPRegeneRate: "帕魯生命值自然回復倍率",
  PalAutoHpRegeneRateInSleep: "帕魯睡眠時自然回復倍率",
  PalEggDefaultHatchingTime: "巨大蛋孵化所需時間(小時)",
  WorkSpeedRate: "工作速度倍率",
  bPalLost: "帕魯死亡後永久消失",
  bAllowGlobalPalboxExport: "允許全域帕魯箱匯出",
  bAllowGlobalPalboxImport: "允許全域帕魯箱匯入",
  EnablePredatorBossPal: "啟用掠食者首領帕魯",
  MonsterFarmActionSpeedRate: "帕魯牧場工作速度倍率",

  ExpRate: "經驗值倍率",
  PlayerDamageRateAttack: "玩家攻擊傷害倍率",
  PlayerDamageRateDefense: "玩家承受傷害倍率",
  PlayerStomachDecreaceRate: "玩家飽食度降低倍率",
  PlayerStaminaDecreaceRate: "玩家耐力降低倍率",
  PlayerAutoHPRegeneRate: "玩家生命值自然回復倍率",
  PlayerAutoHpRegeneRateInSleep: "玩家睡眠時自然回復倍率",
  ItemWeightRate: "物品重量倍率",
  EquipmentDurabilityDamageRate: "裝備耐久損耗倍率",
  bEnablePlayerToPlayerDamage: "會對玩家造成傷害",
  bEnableFriendlyFire: "會對友軍造成傷害",
  bIsPvP: "開啟 PVP",
  DeathPenalty: "死亡懲罰",
  bEnableFastTravel: "啟用快速旅行",
  bIsStartLocationSelectByMap: "根據地圖選擇起始位置",
  bExistPlayerAfterLogout: "登出後角色留在世界中",
  bEnableNonLoginPenalty: "啟用久未登入懲罰",
  bAllowEnhanceStat_Health: "允許強化生命值",
  bAllowEnhanceStat_Attack: "允許強化攻擊力",
  bAllowEnhanceStat_Stamina: "允許強化耐力",
  bAllowEnhanceStat_Weight: "允許強化負重",
  bAllowEnhanceStat_WorkSpeed: "允許強化工作速度",
  AdditionalDropItemWhenPlayerKillingInPvPMode: "PVP 擊殺掉落物品類型",
  AdditionalDropItemNumWhenPlayerKillingInPvPMode: "PVP 擊殺額外掉落數量",
  bAdditionalDropItemWhenPlayerKillingInPvPMode: "啟用 PVP 擊殺額外掉落",
  bDisplayPvPItemNumOnWorldMap_Player: "世界地圖顯示玩家 PVP 掉落數",
  BlockRespawnTime: "重生封鎖時間(秒)",
  RespawnPenaltyDurationThreshold: "重生懲罰時間門檻(秒)",
  RespawnPenaltyTimeScale: "重生懲罰時間倍率",

  GuildPlayerMaxNum: "公會人數上限",
  BaseCampMaxNum: "世界據點數量上限",
  BaseCampMaxNumInGuild: "每個公會的據點數量上限",
  BaseCampWorkerMaxNum: "據點工作帕魯數量上限",
  bAutoResetGuildNoOnlinePlayers: "自動清除長時間離線的公會",
  AutoResetGuildTimeNoOnlinePlayers: "公會離線多少小時後清除",
  bEnableDefenseOtherGuildPlayer: "啟用防禦其他公會玩家",
  bCanPickupOtherGuildDeathPenaltyDrop: "可撿其他公會玩家的死亡掉落物",
  bInvisibleOtherGuildBaseCampAreaFX: "隱藏其他公會據點範圍特效",
  GuildRejoinCooldownMinutes: "重新加入公會冷卻(分鐘)",
  bDisplayPvPItemNumOnWorldMap_BaseCamp: "世界地圖顯示據點 PVP 掉落數",

  BuildObjectDamageRate: "對建築傷害倍率",
  BuildObjectDeteriorationDamageRate: "建築劣化速度倍率",
  bBuildAreaLimit: "限制建築範圍",
  MaxBuildingLimitNum: "每位玩家建築數量上限(0 = 無限)",
  ServerReplicatePawnCullDistance: "角色同步距離(公分)",
  BuildObjectHpRate: "建築物生命值倍率",
  bEnableBuildingPlayerUIdDisplay: "顯示建築物所屬玩家",
  BuildingNameDisplayCacheTTLSeconds: "建築物名稱顯示快取(秒)",

  DropItemMaxNum: "世界內的掉落物上限",
  DropItemAliveMaxHours: "掉落物存在時間(小時)",
  CollectionDropRate: "道具掉落量倍率",
  EnemyDropItemRate: "敵人掉落物品倍率",
  ItemCorruptionMultiplier: "食物腐敗速度倍率",
  SupplyDropSpan: "空投補給間隔(分鐘)",
  DropItemMaxNum_UNKO: "糞便掉落物上限",
  bActiveUNKO: "啟用糞便掉落物",
  PhysicsActiveDropItemMaxNum: "物理模擬掉落物上限",
  DenyTechnologyList: "禁止的科技清單",

  Difficulty: "難度",
  DayTimeSpeedRate: "白天流逝速度",
  NightTimeSpeedRate: "夜晚流逝速度",
  CollectionObjectHpRate: "可採集物品生命值倍率",
  CollectionObjectRespawnSpeedRate: "可採集物品重生間隔",
  bEnableInvaderEnemy: "會發生襲擊事件",
  bEnableAimAssistPad: "啟用手柄瞄準輔助",
  bEnableAimAssistKeyboard: "啟用鍵盤瞄準輔助",
  bHardcore: "硬核模式",
  bCharacterRecreateInHardcore: "硬核模式下可重建角色",
  RandomizerType: "隨機化模式",
  RandomizerSeed: "隨機化種子",
  bIsRandomizerPalLevelRandom: "隨機化帕魯等級",
};

export const ENUM_LABELS: Record<string, string> = {
  None: "無",
  Item: "僅道具",
  ItemAndEquipment: "道具和裝備",
  All: "所有",
  Casual: "輕鬆",
  Normal: "普通",
  Hard: "困難",
  Text: "文字",
  Json: "JSON",
  Region: "區域",
  PlayerDropItem: "玩家掉落物",
  AllItems: "所有物品",
};

export const STATUS_LABELS = {
  running: "運作中",
  installing: "安裝中",
  restarting: "重啟中",
  starting: "啟動中",
  exited: "已停止",
  missing: "容器遺失",
  created: "未啟動",
} as const;
